-- ===========================
-- Add format_type and platform fields to content_ideas
-- ===========================

-- Add format_type column
ALTER TABLE content_ideas
ADD COLUMN IF NOT EXISTS format_type VARCHAR(100);

-- Add platform column
ALTER TABLE content_ideas
ADD COLUMN IF NOT EXISTS platform VARCHAR(50);

-- Add hook_visual column (also missing from schema but required by AI)
ALTER TABLE content_ideas
ADD COLUMN IF NOT EXISTS hook_visual TEXT;

-- Add hashtags column (generated by AI but not stored)
ALTER TABLE content_ideas
ADD COLUMN IF NOT EXISTS hashtags TEXT[];

-- Add production_tips column (generated by AI but not stored)
ALTER TABLE content_ideas
ADD COLUMN IF NOT EXISTS production_tips TEXT[];

-- Add common_mistakes column (generated by AI but not stored)
ALTER TABLE content_ideas
ADD COLUMN IF NOT EXISTS common_mistakes TEXT[];

-- Create index for format_type for faster filtering
CREATE INDEX IF NOT EXISTS idx_content_ideas_format_type ON content_ideas(format_type);

-- Create index for platform for faster filtering
CREATE INDEX IF NOT EXISTS idx_content_ideas_platform ON content_ideas(platform);

-- Add comments for documentation
COMMENT ON COLUMN content_ideas.format_type IS '콘텐츠 포맷 타입 (Challenge, Recipe, ASMR, Comedy, Review, Tutorial)';
COMMENT ON COLUMN content_ideas.platform IS '최적 플랫폼 (tiktok, instagram, youtube)';
COMMENT ON COLUMN content_ideas.hook_visual IS '첫 3초에 보여줄 비주얼 요소';
COMMENT ON COLUMN content_ideas.hashtags IS '추천 해시태그 리스트';
COMMENT ON COLUMN content_ideas.production_tips IS '제작 팁 리스트';
COMMENT ON COLUMN content_ideas.common_mistakes IS '피해야 할 실수 리스트';
